language: python

sudo: false
fast_finish: true

python:
  - "3.4"
  - "3.5"

install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install git+https://github.com/blampe/IbPy/archive/master.zip
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master