language: python

sudo: true
fast_finish: true

python:
  - "3.4"
  - "3.5"

install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install git+git://github.com/blampe/IbPy
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master