language: python

sudo: true
fast_finish: true

python:
  - "3.4"
  - "3.5"

install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8620cd7698be90304ed6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
